name: student_hackerha
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  animated_theme_switcher: ^2.0.10
  animations: ^2.0.11
  audioplayers: ^6.4.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  day_night_switch: ^1.0.4
  day_night_switcher: ^0.2.0+1
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  phosphor_flutter: ^2.1.0
  pin_code_fields: ^8.0.1
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  vibration: ^3.1.3
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/icons/
    - assets/images/
    - assets/audio/audio_2025-04-21_00-53-59.mp3
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/font/Montserrat-Arabic Regular 400.otf
        - asset: assets/font/Montserrat-Arabic Light 300.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
