name: student_hackerha
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  phosphor_flutter: ^2.1.0
  flutter_bloc: ^9.1.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/
fonts:
  - family: Montserrat-Arabic
    fonts:
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-Thin.otf
        weight: 200 
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-Light.otf
        weight: 300
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-Regular.otf
        weight: 400
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-Medium.otf
        weight: 500
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-SemiBold.otf
        weight: 600
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-Bold.otf
        weight: 700
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-ExtraBold.otf
        weight: 800
      - asset: assets/fonts/Montserrat_Arabic_Font_Family_(Fontmirror)/Montserrat-Arabic-Black.otf
        weight: 900