name: student_hackerha
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  animated_theme_switcher: ^2.0.10
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  day_night_switch: ^1.0.4
  day_night_switcher: ^0.2.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/

  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic Regular 400.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic Bold 700.otf
          weight: 700
        - asset: assets/fonts/Montserrat-Arabic Light 300.otf
          weight: 300
